name: IL2 Bridge
version: "1.0.6"
slug: il2_bridge
description: Rekonstruerer strom i L2 fra Aidon 3P3W HAN-data
url: "https://github.com/wesenrog/ha-addons"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
init: false
startup: services
boot: auto
services:
  - mqtt:want
options:
  mqtt_port: 1883
  src_topic: "amsreader/power"
  sequence: -1
  stale_after: 30
  field_u12: "U1"
  field_u31: "U2"
  field_u23: "U3"
  field_i1: "I1"
  field_i3: "I3"
  field_p: "P"
  field_q: "Q"
  field_p_out: "PO"
  field_q_out: "QO"
schema:
  mqtt_host: "str?"
  mqtt_port: "int(1,65535)"
  mqtt_user: "str?"
  mqtt_password: "password?"
  src_topic: str
  sequence: "list(-1|1)"
  stale_after: "int(5,600)"
  field_u12: str
  field_u31: str
  field_u23: str
  field_i1: str
  field_i3: str
  field_p: str
  field_q: str
  field_p_out: str
  field_q_out: str
